### ISSUE TITLE
Card does not display any map, only shows date at top

### ISSUE THREAD

**Issue by u8915055** [zha-ng/zha-map#43]
Hello,

First off im using Home Assistant 0.117.2.  I will state that this has not worked for me since at least .116.0 but it might have been before.

I have zha_map loading fine it seems because im also using the zigzag module and the zha_network_card module and those seem to work fine. 

However, I added the card to a panel view.. but all it shows me is a date at the top (1970-01-01 00:00:00) and a search box.  So it seems the module loaded, but just isnt displaying anything.

![image](https://user-images.githubusercontent.com/35235070/97937477-ab55da00-1d33-11eb-942f-903fc81702e2.png)

My config is:

```
views:
  - panel: true
    badges: []
    cards:
      - type: 'custom:zha-network-visualization-card'
```
Any ideas what might be happening here?

Thanks very much.
